#!/usr/bin/env bash
# Runs every issue's tests unpatched, with its own patches and with all patches,
# then the 6.0.0/5.3.0 unit tests with all patches, and writes verification.md.
#
#   tools/run-all.sh                 everything (results are cached in .build/verify/; --force reruns)
#   tools/run-all.sh ID ...          only these issues (verification.md is still written for all
#                                    issues that have cached results)
#   tools/run-all.sh --no-unit-tests skip the project's unit tests
set -uo pipefail
. "$(dirname "$0")/config.sh"

force=0; unit=1; ids=()
for a in "$@"; do
    case "$a" in
        --force) force=1 ;;
        --no-unit-tests) unit=0 ;;
        *) ids+=("$a") ;;
    esac
done
[ "${#ids[@]}" -eq 0 ] && ids=($(all_issue_ids))

V="$BUILD_ROOT/verify"; mkdir -p "$V"

verdict() {  # $1 = run-test output, $2 = engine label, $3 = variant
    grep -E " $2 $3: " <<<"$1" | tail -1 | sed -E "s/.* $2 $3: //; s/ \(.*//"
}

for id in "${ids[@]}"; do
    f="$V/$id.txt"
    if [ "$force" = 0 ] && [ -s "$f" ]; then continue; fi
    echo "== $id" >&2
    out_base="$("$ROOT/tools/run-test.sh" "$id" -q 2>&1)"
    out_p="$("$ROOT/tools/run-test.sh" "$id" --patched -q 2>&1)"
    out_all="$("$ROOT/tools/run-test.sh" "$id" --all -q 2>&1)"
    {
        echo "524=$(verdict "$out_base" 5.2.4 base)"
        echo "530=$(verdict "$out_base" 5.3.0 base)"
        echo "600=$(verdict "$out_base" 6.0.0 base)"
        echo "530p=$(verdict "$out_p" 5.3.0 patched)"
        echo "600p=$(verdict "$out_p" 6.0.0 patched)"
        echo "530a=$(verdict "$out_all" 5.3.0 all)"
        echo "600a=$(verdict "$out_all" 6.0.0 all)"
    } > "$f"
    cat "$f" | tr '\n' ' ' >&2; echo >&2
done

# ---- unit tests: unpatched tree and all-patches tree
if [ "$unit" = 1 ]; then
    for mode in base all; do
        if [ "$force" = 1 ] || [ ! -s "$BUILD_ROOT/600-$mode$BUILD_SUFFIX/ctest.log" ]; then
            echo "== unit tests ($mode)" >&2
            if [ "$mode" = base ]; then "$ROOT/tools/build-engine.sh" 600 --unit-tests >/dev/null
            else "$ROOT/tools/build-engine.sh" 600 --all --unit-tests >/dev/null; fi
        fi
    done
fi

# ---- verification.md
host="$(uname -sm), $($CC --version 2>/dev/null | head -1)"
{
echo "# Verification"
echo
echo "Generated by \`tools/run-all.sh\` on $(date +%Y-%m-%d) ($host)."
echo
echo "Each test was compiled and run against engines built with AddressSanitizer and UndefinedBehaviorSanitizer:"
echo
echo "- **5.2.4**: EPA SWMM tag v5.2.4, unpatched. 5.2.4 is reviewed but not patched."
echo "- **5.3.0** and **6.0.0**: \`src/legacy/engine\` and \`src/engine\` at cb3e192b, unpatched, then with the issue's own patch (*patched*), then with every patch in this review applied together (*all*)."
echo
echo "Expected: an affected engine shows the bug unpatched (\`FAIL\`, \`CRASH\` or \`HANG\`), an unaffected one \`PASS\`es, and every patched run \`PASS\`es. \`n/a\` means there is no test for that engine (e.g. a 5.3.0-only API). Issues fixed only in documentation are marked *docs fix*."
echo
echo "| ID | 5.2.4 | 5.3.0 | 5.3.0 patched | 6.0.0 | 6.0.0 patched | 5.3.0 all | 6.0.0 all | |"
echo "|---|---|---|---|---|---|---|---|---|"
for id in $(all_issue_ids); do
    f="$V/$id.txt"; [ -s "$f" ] || continue
    get() { sed -n "s/^$1=//p" "$f"; }
    d="$(issue_dir "$id")"
    ok="✓"
    for k in 530p 600p 530a 600a; do [ "$(get $k)" = PASS ] || ok="✗"; done
    note="$ok"
    if [ ! -f "$d/${id}_swmm530.patch" ] && [ ! -f "$d/${id}_swmm600.patch" ]; then
        if ls "$d"/*_docs.patch >/dev/null 2>&1; then note="docs fix"; else note="5.2.4 only, no patch"; fi
        [ "$(get 530)" = PASS ] && [ "$(get 600)" = PASS ] || note="✗ $note"
    fi
    echo "| [$id](${d#$ROOT/}/) | $(get 524) | $(get 530) | $(get 530p) | $(get 600) | $(get 600p) | $(get 530a) | $(get 600a) | $note |"
done
if [ -s "$BUILD_ROOT/600-base$BUILD_SUFFIX/ctest.log" ] && [ -s "$BUILD_ROOT/600-all$BUILD_SUFFIX/ctest.log" ]; then
    echo
    echo "## The project's own unit tests"
    echo
    echo "The 6.0.0 tree's ctest suite (unit tests for both the legacy 5.3.0 library and the 6.0.0 engine) was built with the same sanitizers, unpatched and with all patches."
    echo
    for mode in base all; do
        echo "- **$mode**: $(grep -E 'tests passed' "$BUILD_ROOT/600-$mode$BUILD_SUFFIX/ctest.log" | tail -1)"
    done
    echo
    new="$(comm -13 <(sort "$BUILD_ROOT/600-base$BUILD_SUFFIX/ctest-failed.txt") <(sort "$BUILD_ROOT/600-all$BUILD_SUFFIX/ctest-failed.txt"))"
    fixed="$(comm -23 <(sort "$BUILD_ROOT/600-base$BUILD_SUFFIX/ctest-failed.txt") <(sort "$BUILD_ROOT/600-all$BUILD_SUFFIX/ctest-failed.txt"))"
    echo "Test programs failing with all patches but not unpatched:"; echo
    if [ -n "$new" ]; then sed 's/^/- /' <<<"$new"; else echo "- none"; fi
    echo; echo "Test programs failing unpatched but passing with all patches:"; echo
    if [ -n "$fixed" ]; then sed 's/^/- /' <<<"$fixed"; else echo "- none"; fi
    echo; echo "Test programs failing in both (pre-existing):"; echo
    comm -12 <(sort "$BUILD_ROOT/600-base$BUILD_SUFFIX/ctest-failed.txt") <(sort "$BUILD_ROOT/600-all$BUILD_SUFFIX/ctest-failed.txt") | sed 's/^/- /'
    if [ -f "$ROOT/tools/verification-notes.md" ]; then echo; cat "$ROOT/tools/verification-notes.md"; fi
fi
} > "$ROOT/verification.md"
echo "wrote verification.md" >&2
